입력값과 엔티티 필드에 대한 유효성 검증 구현
woowacourse-teams/2024-mouda pull request #120
Opened 2024-07-25 04:44 UTC by Mingyum-Kim

## PR의 목적이 무엇인가요?

## 이슈 ID는 무엇인가요?

- #

## 설명

## 질문 혹은 공유 사항 (Optional)

2024-07-25 06:05 UTC, ay-eonii reviewed
고생했어요 안나 👍

코멘트 확인 부탁드려용~!!

2024-07-25 06:05 UTC, ay-eonii commented on backend/src/test/java/mouda/backend/moim/domain/MoimTest.java
> +			.time(LocalTime.now().minusHours(1))
```suggestion
			.date(DATE)
			.time(TIME)
```
과거 시간이어서 예외가 발생할 수 있을 것 같아요~!

2024-07-25 06:05 UTC, ay-eonii commented on backend/src/test/java/mouda/backend/moim/domain/MoimTest.java
> +	void createMoimWhenDescriptionIsTooLong() {
```suggestion
	@DisplayName("설명의 길이가 길면 모임 객체 생성에 실패한다.")
	@Test
	void failToCreateMoimWhenDescriptionIsTooLong() {
```

2024-07-25 08:32 UTC, ksk0605 requested changes
고생하셨어요! 몇 가지 코멘트들 확인 부탁드릴게요. 
테스트 픽스쳐 같은 경우는 이번 이슈에서 적용안해도 될거같아요 참고만 부탁드려요 ㅎㅎ

2024-07-25 08:32 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
>  	String title,
클래스 명 이후 한 줄 띄어쓰는 것이 컨벤션 맞죠..?!

2024-07-25 08:32 UTC, ksk0605 commented on backend/src/test/java/mouda/backend/member/repository/MemberRepositoryTest.java
> +			.description("모임 설명입니다.")
반복적인 모임 생성이 슬슬 보이기 시작하군요..!
테스트 픽스쳐 적용도 고려해보시죠!

2024-07-25 08:32 UTC, ksk0605 commented on backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
>  		);
요청 객체도 마찬가지구요! (Test Fixture)

2024-07-26 02:00 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
> +	}
조금 더 이유를 붙여서 설명해주면 좋을 것 같아요 -!

2024-07-26 02:00 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
>  	String title,
Record의 경우에는 이 부분이 파라미터에 해당해서 안 띄는 게 맞다고 생각했어요 👍

2024-07-27 07:04 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
> +	}
논리적인 이유는 없고 ..
오버라이딩한 메서드보다 GlobalExceptionHandler 만이 가진 메서드(`handleMoudaException`, `handleException`)가 클래스를 더 잘 나타낸다는 느낌이 있어서 위에 말한 방식을 선호하는 것 같아요 ㅎ_ㅎ

2024-07-27 07:04 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
> +	}
논리적인 이유는 없고 ..
오버라이딩한 메서드보다 GlobalExceptionHandler 만이 가진 메서드(handleMoudaException, handleException)가 클래스를 더 잘 나타낸다는 느낌이 있어서 위에 말한 방식을 선호하는 것 같아요 ㅎ_ㅎ

2024-07-27 07:15 UTC, hoyeonyy approved these changes
꼼꼼하게 검증 처리해준 안나에게 발박수 드립니다,,

테바가 제안해준 test fixture가 슬슬 필요할 시기라고도 느껴지네요!

고생하셨습니다! approve 남길께요!

2024-07-27 07:15 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/moim/controller/MoimController.java
> +	public ResponseEntity<RestResponse<MoimDetailsFindResponse>> findMoimDetails(@PathVariable("moimId") Long moimId) {
이 코드는 조금 더 명시적인 측면에서 작성하신 건가요?!

2024-07-27 07:15 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/moim/domain/Moim.java
> +	private void validateTitle(String title) {
안나의 꼼꼼함에 발박수 드립니다.

2024-07-27 07:15 UTC, hoyeonyy approved these changes

2024-07-27 07:16 UTC, hoyeonyy approved these changes
꼼꼼하게 검증처리를 해준 안나에게 발 박수 드립니다,,

테바가 제안해준 Test Fixture를 도입해야 될 때가 된것 같긴하네요..!

고생하셨습니다~! approve 할께요!

2024-07-27 09:40 UTC, pricelees commented on backend/src/main/java/mouda/backend/moim/controller/MoimController.java
> +	public ResponseEntity<RestResponse<MoimDetailsFindResponse>> findMoimDetails(@PathVariable("moimId") Long moimId) {
> 이 코드는 조금 더 명시적인 측면에서 작성하신 건가요?!

moimId를 명시하지 않았을때 안나 테스트가 터지더라고~! 머지 되면 각자 컴퓨터에서 다시 돌려서 확인해봐용~~

2024-07-27 10:03 UTC, pricelees requested changes
안나 고생많았어~!👍

> MIN, MAX 등의 상수와 validate 함수로 인해 엔티티가 너무 > 길어지는 문제가 있었습니다.
> VO 사용 등을 통해 해당 문제와 중복 코드를 해결할 수 있을 것 > 같습니다.

아직은 괜찮은 것 같아요!

> 앞서 설명 드린 유효성 검증에 대한 의견이 궁금합니다 😄
> 엔티티와 DTO에 대해 유효성 검증 역할이 적절히 분배된 게 맞나요?

저는 좋아요~! 역할에 따라 꼼꼼히 잘 해주신 것 같습니다!

2024-07-31 02:12 UTC, Mingyum-Kim commented on backend/src/test/java/mouda/backend/moim/domain/MoimTest.java
> +			.time(LocalTime.now().minusHours(1))
과거 시간을 테스트하는 게 맞아요 😀

2024-07-31 02:15 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/moim/domain/Moim.java
> +		if (description != null && description.length() > DESCRIPTION_MAX_LENGTH) {
description은 NULL이 가능하기 때문에 위와 같이 처리하였습니다 👍

2024-07-31 02:20 UTC, pricelees approved these changes
굿~~!!

2024-07-31 02:20 UTC, ksk0605 approved these changes
고생했어요 안나~

2024-07-31 02:25 UTC, merged