채팅방 목록 미리보기 api 구현 및 마지막으로 읽은 채팅 필드 추가
woowacourse-teams/2024-mouda pull request #247
Opened 2024-08-06 08:30 UTC by hoyeonyy

## PR의 목적이 무엇인가요?

- 채팅방 목록 미리보기 api 구현
- 마지막으로 읽은 채팅 필드 추가

## 이슈 ID는 무엇인가요?

- #241 

## 설명

<img width="759" alt="image" src="https://github.com/user-attachments/assets/eea768a5-3e08-4d09-a461-ec5a328d1557">

채팅방 목록 미리보기을 위한 api 구현

이 api를 폴링하여 채팅방 미리보기를 렌더링합니다.

마지막으로 읽은 채팅에 대한 값을 참여 테이블에 넣었습니다.
이를 이용하여 읽지 않은 메세지의 개수를 카운트합니다.

## 질문 혹은 공유 사항 (Optional)

2024-08-06 09:11 UTC, Mingyum-Kim requested changes
리뷰 남겼어요 호기 ! 👍 
확인 부탁드립니다~

2024-08-06 09:11 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +			throw new ChatException(HttpStatus.BAD_REQUEST, ChatErrorMessage.MOIM_NOT_FOUND);
멤버 아이디를 기준으로 참여 정보를 조회하고, 아무것도 참여하고 있지 않으면 에러를 터뜨리고 있네요!
참여하는 목록이 없으면 에러를 터뜨리는 게 적합할 지 고민해봅시다 😄 

만약 에러를 던진다면 에러 메세지는 MOIM_NOT_FOUND보단 다른 게 좋을 것 같아요.

2024-08-06 09:11 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +			.toList();
모임이 열려있는 지 (`isChatOpened`) 를 확인하고 열려있는 모임만 조회하는 로직을 추가해야할 것 같아요. 👍

2024-08-06 10:09 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/dto/response/ChatPreviewResponse.java
> +			.lastContent(chat.getContent())
호기 ~ 이거 채팅이 아예 없는 상태의 채팅 프리뷰라면 NPE가 뜰 것 같아요. 
소파 말로는 채팅이 아예 없다면 빈 문자열이 왔으면 좋겠다고 하네요!
확인 부탁해요 ~

2024-08-06 10:43 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +			.toList();
좋은 지적 고마워요! 필터로 추가할께요!

2024-08-06 10:43 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/chat/dto/response/ChatPreviewResponse.java
> +			.lastContent(chat.getContent())
확인해서 수정하겠씁니다~!

2024-08-06 11:04 UTC, ay-eonii approved these changes

2024-08-06 11:04 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +				Chat chat = chatRepository.findLastByOrderById();
이 부분이 말씀드린 `IncorrectResultSizeDataAccessException` 발생하는 부분입니다 ~!

2024-08-06 11:38 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +			throw new ChatException(HttpStatus.BAD_REQUEST, ChatErrorMessage.MOIM_NOT_FOUND);
소파랑 이야기해서 빈 list를 던져주기로 했습니다!

2024-08-06 12:06 UTC, Mingyum-Kim approved these changes
호기짱은 잘 해냈을 거라고 믿고 미리 Approve 드리겠습니다! 
고생했어요 ~ 나머지는 내일 뚝딱뚝딱해봅시다

2024-08-07 02:19 UTC, ay-eonii approved these changes
좋아용~~ 고생하셨습니다 👍

2024-08-07 02:28 UTC, merged