채팅방에서 날짜, 시간, 장소를 확정하는 기능 구현
woowacourse-teams/2024-mouda pull request #248
Opened 2024-08-06 08:31 UTC by Mingyum-Kim

## PR의 목적이 무엇인가요?

채팅 방에서 날짜와 시간, 장소를 확정한다.

## 이슈 ID는 무엇인가요?

- #237 

## 설명

-  날짜, 시간 확정 기능 구현
- 장소 확정 기능 구현
-  존재하지 않는 모임 예외 처리
- 빈 문자열이나 NULL 예외 처리
-  작성자가 아닌 경우 예외 처리
- 모임 날짜와 시간을 모임 데이터에서 수정한다.
- 모임 장소를 모임 데이터에서 수정한다.

## 질문 혹은 공유 사항 (Optional)

2024-08-06 09:12 UTC, ay-eonii requested changes
좋아요~ 어노테이션 빠진 부분만 수정하면 될 것 같아용 👍

2024-08-06 09:12 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/chat/controller/ChatController.java
> +	public ResponseEntity<Void> confirmDateTime(DateTimeConfirmRequest dateTimeConfirmRequest, Member member) {
어노테이션이 빠진거 같아요~!

2024-08-06 09:19 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +		moim.confirmPlace(placeConfirmRequest.place());
여기서 문자열 길이 검사 등이 안됨 .. 🥺

2024-08-06 09:19 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +		moim.confirmDateTime(dateTimeConfirmRequest.date(), dateTimeConfirmRequest.time());
여기서 이전 날짜에 대한 검증 등이 안됨 .. 🥺

2024-08-06 11:15 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/controller/ChatController.java
> +	public ResponseEntity<Void> confirmDateTime(DateTimeConfirmRequest dateTimeConfirmRequest, Member member) {
네넵 감사해요! 수정했어요!

2024-08-07 01:56 UTC, ay-eonii approved these changes
고생하셨습니당 👍

2024-08-07 02:02 UTC, pricelees approved these changes
굿 ~👍

2024-08-07 02:02 UTC, pricelees commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +		findChamyoByMoimIdAndMemberId(chatCreateRequest.moimId(), member.getId());
`findChamyoByMoimIdAndMemberId`에 반환값이 없는데 존재 여부에 대한 검증을 위한건가요?? 검증이 목적이면 exist~ 를 사용해서 별도의 validation을 만드는게 더 이해가 쉬울 것 같아요!

2024-08-07 02:02 UTC, hoyeonyy approved these changes
안나 코딩 잘..할까?

2024-08-07 02:08 UTC, ksk0605 approved these changes
안나치~ 고생했어요 몇가지 코맨트 남겨두었으니 읽어주세요!

2024-08-07 02:08 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/controller/ChatController.java
> +		return ResponseEntity.ok().build();
**확정하다** 라는 워딩에 대해서 고민되는 지점이 생겼어요! 
장소나 시간,날짜를 수정할 때도 결국 같은 API 를 사용하게 될 것 같아서요!
안나가 말해준 것 처럼 '장소 공지하기' 라는 워딩이 더 잘 어울릴 것 같네요.

아 그리고 사용자들의 현재 확정된 장소/시간/날짜를 알 수 있도록 GET API도 추가하면 좋겠네요 😀

2024-08-07 02:08 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
>  		}
'최근 채팅 ID 가 0보다 작으면 안된다'
라는 의미의 코드인 것 같아요. 

고민해볼 지점이 있을 것 같은데 
모든 채팅ID는 0보다 커야하는데 특별히 최근 id만 0보다 크다는 조건을 
서비스 레이어에서 체크하고 있는 것이 약간 어색하게 느껴져요! 

검증 로직의 성격에 따라 적절한 위임 장소를 같이 고민해봐요!

2024-08-07 02:48 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/dto/request/DateTimeConfirmRequest.java
> +			.content(date.toString() + " " + time.toString())
오 좋은데요?

2024-08-07 05:24 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
> +		findChamyoByMoimIdAndMemberId(chatCreateRequest.moimId(), member.getId());
여기서는 사용하고 있지 않은데 다른 부분에서 반환값을 사용하고 있어서요! 
피드백 감사합니다 ~

2024-08-07 05:30 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/service/ChatService.java
>  		}
생각해보니 ID를 일일이 다 검증할 필요가 없을 것 같네요 .. 😃  이 부분은 지우도록 하겠습니다. 검증을 하지 않는게 컨벤션에 더 맞는 것 같아요. 지적 감사합니당

2024-08-07 06:01 UTC, merged