알림 기능 추상화로 리팩토링
woowacourse-teams/2024-mouda pull request #513
Opened 2024-08-31 08:39 UTC by ksk0605

## PR의 목적이 무엇인가요?

여러 Service 객체의 알림 관련 의존성으로 인한 유지보수 및  관리 어려움 해결 

## 이슈 ID는 무엇인가요?

- #508 

## 설명

코드 변경이 많아서 글로만 이해가 안될 수 있어요! 필요하다면 꼭 제게 물어봐주세요!!!!!!!

1. 알림을 보낼 수 있는 서비스(MoimService, ChatService, ChamyoService)가 Notification 관련 기능과 너무 많은 연관관계를 맺고 있음. → 유지보수 어려움
2. 사실상 같은 기능임에도 10 줄 정도의 반복적인 코드들이 산재해 있음 
3. 의존성으로 인한 도메인 로직의 손상위험 있음.
4. FCM 관련 의존성이 NotificationService와 높은 의존성을 가짐으로 인해 테스트 코드 작성에 어려움

위 같은 현상이 반복되는 이유는 모우다의 알림 기능에 다음과 같은 요구사항이 있기 때문. 

#### 요구사항

1. 알림의 종류를 구분할 수 있다. 
    1. 색상에 따른 알림 종류 변경
    2. 같은 모임 알림이라고 하더라도 종류가 다름(모임 생성, 댓글 등)
    3. 채팅은 알림을 보내지 않고 알림 센터에만 보여줌
2. 알림을 보낼 사람을 선별할 수 있다. 
    1. 전체
    2. 자기 제외, 방에 있는 사람들만
    3. 답글이 달린 댓글 작성자만 
    5. 등등

#### 해결방안
##### FCM 관련 의존성을 NotificationService와 분리
```java
public class FcmService {

	private final FcmTokenRepository fcmTokenRepository;

	public void sendNotification(MoudaNotification notification, List<String> tokens) {
		if (tokens.isEmpty()) {
			return;
		}
        ...
```
결과 : __알림 기능 중 `FcmService` 를 테스트 코드에서 대체할 Mock 객체를 만들어서 테스트 가능__

##### 전략 패턴으로 알림 종류에 따른 알림 빌더, 송신자 결정 로직 분리 
위 요구사항들은 같은 기능이라도 ‘전략’에 따른 다른 동작을 하기를 원함
 → 전략 패턴을 통한 개선

```java
// 알림 빌더 전략 인터페이스
public interface NotificationBuilderStrategy {

	MoudaNotification buildNotification(Long darakbangId, Moim moim, DarakbangMember sender);
}

```

```java
// 알림 송신 대상 전략 인터페이스
public interface RecipientResolverStrategy {

	List<Long> resolveRecipients(long darakbangId, MoudaNotification notification, Moim moim,
		DarakbangMember sender);
}
```

**결과** 
```java
public void notifyToMembers(NotificationType type, Long darakbangId, Moim moim, DarakbangMember sender) {
    MoudaNotification notification = notificationFactory.getStrategy(type)
	    .buildNotification(darakbangId, moim, sender);
    List<Long> recipients = recipientFactory.getStrategy(type)
	    .resolveRecipients(darakbangId, notification, moim, sender);
    
    List<String> tokens = fcmTokenRepository.findAllTokenByMemberIds(recipients);
    fcmService.sendNotification(notification, tokens);
    }
```
NotificationType 에 다라 다른 알림 생성,송신자 계산 결정 로직이 결정되도록 수정됨. 

```java
@Component
@NotificationTypeProvider(NotificationType.MOIM_CANCELLED)
public class MoimCancelledNotificationBuilder extends MoimNotificationBuilder {

	public MoimCancelledNotificationBuilder(
		MoudaNotificationRepository moudaNotificationRepository) {
		super(moudaNotificationRepository);
	}

	@Override
	public MoudaNotification buildNotification(Long darakbangId, Moim moim, DarakbangMember sender) {
		NotificationType notificationType = NotificationType.MOIM_CANCELLED;
		MoudaNotification notification = MoudaNotification.builder()
			.type(notificationType)
			.body(notificationType.createMessage(moim.getTitle()))
			.targetUrl(baseUrl + String.format(moimUrl, darakbangId, moim.getId()))
			.build();

		return moudaNotificationRepository.save(notification);
	}
}
```
**새로운 알림 종류가 생겼을 때에는 전송 전략을 구현하는 객체를 추가하는 것으로 확장성 개선**

## 질문 혹은 공유 사항 (Optional)

- 구현체별로 공통 코드들을 abstract class 로 분리해놓은 경우가 있어서 혹시 이해가 안되면 물어봐주세요!
- 추가로 AOP 를 적용시켜놓으려했으나 
  ```java
	private void sendCommentNotification(Moim moim, DarakbangMember author, Long parentId, Long darakbangId) {
		if (parentId != null) {
			Long parentCommentAuthorId = commentRepository.findMemberIdByParentId(parentId);
			notificationService.notifyToMember(NotificationType.NEW_REPLY, darakbangId, moim, author,
				parentCommentAuthorId);
		}

		notificationService.notifyToMembers(NotificationType.NEW_COMMENT, darakbangId, moim, author);
	}

   ```
   위 로직 한 곳에서 parentId 라는 클라이언트에서 보내주는 데이터에 대한 의존이 생겨서 고민중입니다. 함께 이야기 해봐요!

2024-09-02 06:58 UTC, pricelees requested changes
코드량이 엄청나네.. 일단 고생 많이 했음!👍👍 그리고 고생한 만큼 나도 최대한 열심히 봤고😄

전체적인 방향에는 이견이 없지만 구현 방법에 대해서는 다른 생각이 있어서 이것만 별도 커멘트로 남겨놓을게! 

\+ 시간 나면 컨벤션 통일도 한번 하면 좋겠음!

2024-09-04 08:47 UTC, pricelees approved these changes

2024-09-04 08:47 UTC, ay-eonii approved these changes

2024-09-04 08:48 UTC, hoyeonyy approved these changes

2024-09-04 08:49 UTC, merged