다락방, 다락방 멤버 기능 리팩토링
woowacourse-teams/2024-mouda pull request #540
Opened 2024-09-09 12:37 UTC by Mingyum-Kim

## PR의 목적이 무엇인가요?

다락방, 다락방 멤버 기능 리팩토링

## 이슈 ID는 무엇인가요?

- #533 

## 설명

## 질문 혹은 공유 사항 (Optional)

2024-09-10 06:58 UTC, ay-eonii approved these changes

2024-09-10 06:58 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/darakbang/presentation/response/DarakbangResponses.java
> +				.build())
위 response도 정팩메로 만들면 좋을 것 같아요!

2024-09-10 06:58 UTC, ay-eonii commented on backend/src/test/java/mouda/backend/common/fixture/DarakbangFixture.java
> +			.code("SOFABAC")
ㅋㅋㅋㅋ

2024-09-10 07:15 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/darakbang/domain/Darakbangs.java
> +public class Darakbangs {
이름이 왜케 짜쳐보이죠?

2024-09-10 07:15 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +@Service
저희 이거 component 로 하기로 했..을..껄..요..? 아..마..도..?

2024-09-10 07:15 UTC, hoyeonyy approved these changes
안나 고생했어요~!

2024-09-10 07:18 UTC, pricelees approved these changes
고생 많았어~~!!

2024-09-10 07:49 UTC, ksk0605 requested changes
안나 고생했어요! 작업이 만만치 않았을텐데 수고해줘서 고마워요.
코멘트 확인 부탁드려요😀

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		return darakbangWriter.save(darakbangCreateRequest.name(), darakbangCreateRequest.nickname(), member);
save 는 개인적으로 DB 관점에서의 용어라고 생각해요! 저는 append 를 사용했는데 통일할 필요가 있겠네요. 

저는 append 를 제안하고 싶은데 어떤가요?

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		memberValidator.validateNotManger(member);
validateNot망거는 뭐죠? ㅋㅋㅋ

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		Darakbang darakbang = darakbangFinder.findByCode(code, DarakbangErrorMessage.INVALID_CODE);
인자에 에러 메시지가 같이 들어가는 이유가 뭔가요?

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		Darakbang darakbang = darakbangFinder.findByCode(code, DarakbangErrorMessage.INVALID_CODE);
DarakbangFinder 에서 서비스 메서드에 따라 다른 예외메시지를 발생시키고 싶었던 것 같네요!

다만 **서비스 레이어가 어떤 예외 메시지를 던질지 결정하는 것은 비즈니스 로직을 추상화하는 서비스 객체의 역할에서 
벗어난다고 생각**해요! 어**떤 예외 메시지인가? 는 구현 레벨의 관점**이라고 저는 바라보고 있습니다. 

만약 위의 구조가 **어떤 UI에서 발생하는지에 따라 다른 예외 메시지를 출력한다**는 요구사항에 의한 것이었다면
**UI가 백엔드 코드를 결정하는 요소**가 되니 더욱 기피해야하는 상황이 되겠죠!

개인적으로는 예외 메시지는 인자로 받지 않고 Finder 내부로 숨기는 것이 좋을 것 같은데 어떤가요!

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +@Service
이 부분에 대해선 다른 멤버들이랑 통일하는 과정이 필요할 것 같아요! 
구현레이어가 Service 인가? Component 인가? 는 철학적인 논쟁이 될 가능성이 있어서 
컨벤션으로 정하기만 한다면 문제 없을 것 같아요.

추후에 커스텀 어노테이션으로 `@Implement` 를 만들어서 구현 레이어 객체들에게 달아주는 것도 논의해봐요!
명시적인 레이어 구분에 도움이 될 것 같아요😀

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +		darakbangMemberWriter.saveManager(darakbang, nickname, member);
**'다락방 매니져를 추가한다'** 라는 도메인 로직은 Finder에 숨겨져 있어도 괜찮을까요? 
서비스 코드를 읽는 사람 입장에서는 다락방을 추가했을 뿐인데 (물론 인자에 Member가 있지만) 
다락방 관리자도 생기는 것을 해당 코드를 열어봐야 인지할 수 있겠네요. 

물론 **'다락방이 생기면 당연히 매니져가 추가되어야지' 라는 사고가 더 자연스럽다고 생각**하신다면 위 로직이 해당 위치에 존재하는 것이 어색하지 않을 수 있어요.

안나 생각은 어떤가요?

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +		return invitationCode;
'이미 존재하는 코드와 겹치는지 확인한다'는 검증 코드를 `invitationCodeGenerator` 에게 넘겨주는 것은 어떨까요? 
위 코드도 물론 나쁘지 않지만 초대 코드 생성기를 사용하는 클라이언트 입장에서는 직접 코드를 꺼내서 검증하기 보다는 
생성해줘! 라는 메시지의 결과 값을 바로 사용하는 것이 더 자연스러울 것 같다는 의견이에요. 객체지향의 관점에서 말이죠.

안나의 생각은 어떤가요?

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbangmember/domain/DarakBangMemberRole.java
> +	OUTSIDER
상처를 치료해줄 사람 어디 없나 가만히 놔두다간 끊임없이 덧나

2024-09-10 07:49 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/darakbangmember/implement/DarakbangMemberWriter.java
> +	private final DarakbangMemberRepository darakbangMemberRepository;
이 구현레이어를 포함해서 다른 구현레이어들의 단위 테스트가 필요하지 않을까요?

2024-09-10 10:58 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/domain/Darakbangs.java
> +public class Darakbangs {
힝

2024-09-10 10:59 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +@Service
일단 `@Component`로 할게요 ㅎㅎ 이 부분도 같이 이야기해봅시다

2024-09-10 11:18 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		return darakbangWriter.save(darakbangCreateRequest.name(), darakbangCreateRequest.nickname(), member);
이거랑 위에서 말한 어노테이션 관련해서 같이 이야기해보면 좋겠어요. 
DB 관점에서 메서드를 작성하는 거는 저도 지양해야할 바라고 생각합니다 ~

2024-09-10 11:18 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		memberValidator.validateNotManger(member);
🥺 실수 티비

2024-09-10 11:25 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
> +		Darakbang darakbang = darakbangFinder.findByCode(code, DarakbangErrorMessage.INVALID_CODE);
이렇게 밖에 리팩토링하지 못한 것은 같은 조회 쿼리임에도 예외 메시지가 다르기 때문인데요 😢
같은 조회 쿼리임에도 예외 메시지가 다르다  = 데이터베이스가 예외 처리를 담당하고 있다의 의미여서, 저도 수정할 여지가 있어보입니다. ㅎㅎ 
클라이언트와 이야기해서 가능하다면 바꿔놓을게요.

2024-09-10 11:27 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +		darakbangMemberWriter.saveManager(darakbang, nickname, member);
음 .. 저도 다락방 멤버를 해당 부분에서 저장한다는 것을 한번에 이해하지 못했어요. 코드를 봐야 이해할 수 있는 부분인 것 같습니다 😁

테바 말대로 서비스 레이어로 빼서 명시적으로 드러내도록 할게요!

2024-09-10 11:47 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
> +		return invitationCode;
좋은 것 같아요 ~ 유효한 참여 코드를 반환하는 것도 `Generator`의 역할이 될 수 있을 것 같아요 ! 반영해두었습니다

2024-09-10 11:54 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/darakbangmember/implement/DarakbangMemberWriter.java
> +	private final DarakbangMemberRepository darakbangMemberRepository;
흑흑티비 저는 서비스 레이어만 하면 된다고 생각했어요
돌이켜보니 그렇네요  ..
테스트 추가해놓을게요 ~

2024-09-24 07:59 UTC, ksk0605 approved these changes
고생하셔
ㅅ아ㅓㅇㅎ

2024-09-24 07:59 UTC, merged