해주세요, 관심있어요 도메인 리팩토링
woowacourse-teams/2024-mouda pull request #541
Opened 2024-09-10 06:54 UTC by hoyeonyy

## PR의 목적이 무엇인가요?

해주세요, 관심있어요 도메인에 대한 리팩토링

## 이슈 ID는 무엇인가요?

- #528 

## 설명

- implement 레이어 추가
- implement 단위 테스트 구현
- PleaseWithInterest 구현

## 질문 혹은 공유 사항 (Optional)

2024-09-10 07:13 UTC, ay-eonii approved these changes
서비스 레이어 가독성이 정말 좋아졌어요 👍

코멘트 몇가지 남겼습니다!

2024-09-10 07:13 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/please/implement/InterestValidator.java
> +	public void validate(Please please, Long darakbangId, boolean isInterested, DarakbangMember darakbangMember) {
해당 파라미터 전부 필요한가용..?

2024-09-10 07:13 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/please/business/InterestService.java
> +		interestWriter.changeInterest(please, darakbangId, request.isInterested(), darakbangMember);
pleaseFinder 에서 darakbangId와 같이 조회하고
changeInterest는 please 선에서 해결하는 게 어떤가용???

해주세요 관심을 변경할 때 다락방의 해주세요인지 검증하는 것보다, 해주세요를 조회할 때 검사하는 게 인지가 더 잘 될 것 같아요!

2024-09-10 07:13 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/please/business/InterestService.java
> +		interestWriter.changeInterest(please, darakbangId, request.isInterested(), darakbangMember);
```suggestion
		Please please = pleaseFinder.find(request.pleaseId(), darakbangId);
		interestWriter.changeInterest(please, request.isInterested(), darakbangMember);
```

2024-09-10 07:13 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/please/domain/PleaseWithInterests.java
> +			.map(pleaseWithInterest -> PleaseFindAllResponse.toResponse(pleaseWithInterest.getPlease(),
pleaseWithInterest 객체를 넘겨줘도 좋을 것 같아요

2024-09-10 07:19 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/please/implement/InterestValidator.java
> +	public void validate(Please please, Long darakbangId, boolean isInterested, DarakbangMember darakbangMember) {
너 눈썰미 미쳤다. 수정완료.

2024-09-10 07:29 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/please/business/InterestService.java
> +		interestWriter.changeInterest(please, darakbangId, request.isInterested(), darakbangMember);
수정완료!

2024-09-10 07:34 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/please/domain/PleaseWithInterests.java
> +			.map(pleaseWithInterest -> PleaseFindAllResponse.toResponse(pleaseWithInterest.getPlease(),
수정완완료

2024-09-10 08:17 UTC, ksk0605 requested changes
호기 고생많았어요! 작업량이 만만치 않았을텐데 수고했네요 👍
코멘트 확인해주세요!

2024-09-10 08:17 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/please/implement/InterestFinder.java
> +
혹시 해당 코드를 Optional 반환이 아닌 Interest 도메인 반환으로 변경하는 것은 어떤가요? 
```java
class InterestOfPlease { // 클래스 명은 가명
    private final boolean isInterested; 
    
    public InterestDomain(boolean isInterested) {
        this.isInterested = isInterested;
    }
    
    public boolean isInterested() {
        return isInterested;
    }
}
```
```java
public Optional<Interest> findInterest(Long darakbangMemberId, Long pleaseId) {
    Optional<Interest> interest = interestRepository.findByDarakbangMemberIdAndPleaseId(darakbangMemberId, pleaseId);
    if (interest.isPresent()) return new InterestOfPlease(true);
    return new InterestOfPlease(false);
}
```

실제 사용하는 서비스에서는 optional.isPresent()를 확인할 필요 없이 InterestOfPlease 에게 `isInterested()` 라는 메시지를 비즈니스 문제를 추상화 할 수 있겠네요.

호기의 생각은 어떤가요?

2024-09-10 08:17 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/please/implement/InterestValidator.java
> +	}
please에 대한 검증을 InterestValidator에서 진행하는 이유가 있을까요?

2024-09-10 08:17 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/please/implement/PleaseFinder.java
> +		interestValidator.validate(please, darakbangId);
위 InterestValidator 와 동일한 질문이에요! Please 검증을 PleaseValidator 하지 않고 interestValidator 를 사용하는 이유가 있나요?

2024-09-10 08:22 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/please/implement/InterestValidator.java
> +	}
코드 리팩하면서 꼬인거 같아요ㅠ 수정중!

2024-09-24 08:00 UTC, ksk0605 approved these changes
고생하
셔
ㅅ어요ㅗ

2024-09-24 08:00 UTC, merged