Feature/#566
woowacourse-teams/2024-mouda pull request #589
Opened 2024-09-29 07:39 UTC by ay-eonii

## PR의 목적이 무엇인가요?

안내면 진다 기능을 추가합니다.
API
- 안내면진다 목록 조회
- 안내면진다 생성
- 안내면진다 상세조회
- 안내면진다 참여
- 안내면진다 결과 조회
- 안내면진다 결과 강제 도출

## 이슈 ID는 무엇인가요?

- close #566 

## 설명

- DB와의 연관성을 줄이기 위해 Domain 객체와 Entity 객체를 분리해서 설계했습니다.
- N 분후 추첨을 진행하는 서비스 기획에 따라 1분당 스케줄러가 작동하도록 구현했습니다.
  - 특정 스레드가 N 분동안 대기 하는 것은 낭비가 심하다고 생각해 스케줄링을 사용하는 방식을 채택했습니다.
  - 테스트의 경우는 1ms 마다 동작합니다.

## 질문 혹은 공유 사항 (Optional)

- 도메인별 예외처리의 경우 추후에 보완할 예정입니다.
- 프론트의 우선적인 swagger 문서 조회 및 테스트를 위해 먼저 dev 서버에 배포하고자 합니다.

2024-09-29 07:40 UTC, hoyeonyy commented
pr 제목 진짜 열받네요.

2024-09-29 08:35 UTC, Mingyum-Kim commented
안내면진다 목록 조회
안내면진다 생성
안내면진다 상세조회
안내면진다 참여
안내면진다 결과 조회
안내면진다 결과 강제 도출

ㅋㅋㅋㅋㅋㅋㅋㅋ
좀 무섭네요

2024-09-29 15:48 UTC, ksk0605 requested changes
일단 정렬기능을 같이 개발하고 난 후에 머지하는 것으로 하시죠! 
3일만에 신기능 개발하느라 고생많았습니다 ㅋㅋ

2024-09-29 15:48 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/presentation/response/ParticipantResponse.java
> +		);
소셜 로그인 리팩토링 팀 완료되면 같이 이야기해봅시다!

2024-09-29 15:48 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/business/BetScheduler.java
> +		bets.forEach(Bet::draw);
fixedDelay는 이전 작업이 완료된 시점으로부터 주어진 시간 간격에 맞춰 작업을 실행하고
cron 표현식을 사용할 때는 항상 지정된 시간이 되면 항상 xx분 00초에 작동되는 방식이라고 합니다. 

저희 도메인에는 cron 표현식이 더 적절한 듯해서 해당 부분 수정해야할 것 같아요!

2024-09-29 15:48 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/business/BetService.java
> +		return BetFindAllResponses.toResponse(bets);
정렬기준 구현도 필요하겠네요. 
가장 마감시간이 임박한 순서대로 정렬기능 같이 구현해보죠!

2024-09-29 15:48 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/implement/BetFinder.java
> +
예외 처리 공통화는 별도의 이슈를 파서 진행하도록 하시죠!

2024-09-30 14:34 UTC, ksk0605 approved these changes
정렬기능, 크론 설정 완료되었습니다! 고생했어요~

2024-10-01 03:15 UTC, pricelees requested changes
분량이 상당히 많네요..오우.. 고생하셨어요

2024-10-01 03:15 UTC, pricelees commented on backend/src/main/java/mouda/backend/bet/entity/BetEntity.java
> +	}
도메인과 엔티티를 분리했는데, 이러면 엔티티에 어차피 도메인 의존이 생겨서 분리의 장점이 크게 느껴지지 않는 것 같아요. 차라리 별도의 팩토리로 분리하는 등 의존을 제거하면 좋겠음다

2024-10-01 03:15 UTC, pricelees commented on backend/src/main/java/mouda/backend/bet/implement/BetSorter.java
> +        LocalDateTime now = LocalDateTime.now().withSecond(0).withNano(0);
코드 전반적으로 withSecond, withNano가 중복되는데 이걸 한곳에 모아서 조금 더 의미있게 바꿀 수 있겠네요.

2024-10-01 03:18 UTC, pricelees approved these changes

2024-10-01 05:39 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/implement/BetFinder.java
> +					.build();
오 맞습니다! 보니까 ParticiapantFinder의 로직과 겹치는 부분도 있어서 함께 분리해봤습니다.

2024-10-01 05:39 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/presentation/request/BetCreateRequest.java
> +public record BetCreateRequest(
아직 valid 를 고려하지 않았어요. 예외처리 공통화와 함께 진행하려합니다. 꼼꼼한 리뷰 감사해요!

2024-10-01 05:44 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/entity/BetEntity.java
> +	}
개인적인 의견을 말씀드리면 엔티티와 도메인의 분리는 의존성 때문도 있지만 도메인 로직의 순수성을 지킨다는 목적에 더 가까워요. 

기존처럼 도메인과 엔티티가 합쳐진 형태는 말 그대로
1. 도메인 로직을 수행하는 역할
2.DB의 데이터를 가져오는 역할
이 합쳐진 형태니 **SRP를 위반한다** 라고 볼 수도 있구요. 

물론 상돌 말처럼 의존성의 관리도 매우 중요하다고 생각합니다! 
다른 팀원들의 동의하에 Factory 혹은 Mapper 클래스를 도입해볼 수 있겠습니다. 
패턴은 일관적이면 좋으니까요!

2024-10-01 06:42 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/bet/implement/BetSorter.java
> +        LocalDateTime now = LocalDateTime.now().withSecond(0).withNano(0);
BettingTime 객체로 추상화했어요! 좋은 리뷰 감사합니다.

2024-10-01 06:42 UTC, merged