채팅방 정보 가져오기 API 구현
woowacourse-teams/2024-mouda pull request #636
Opened 2024-10-12 15:30 UTC by ksk0605

## PR의 목적이 무엇인가요?

변경된 요구사항(안내면진다 도메인의 채팅방 오픈 기능) 에 맞추어 채팅방 디테일 정보 가져오기 API 구현

## 이슈 ID는 무엇인가요?

- #626 

## 설명

- 기존 모임기능의 연장선으로 기획했던 채팅 기능을 신기능인 안내면진다로 확장
- 이때 채팅방이 모임/안내면진다 중 어느 기능으로 부터 확장되어있는지에 따라 정보의 차이가 있으며 UI 출력에 차이가 있음
- 유연한 사용자 UI 출력을 위해 attributes 라는 key 의 값으로 map 형태로 전달하기로 결정 

### 예시
#### 모임
<img width="427" alt="Screenshot 2024-10-13 at 12 29 57 AM" src="https://github.com/user-attachments/assets/331b2306-b423-440c-8edc-33c88080c955">

#### 안내면진다
<img width="477" alt="Screenshot 2024-10-13 at 12 30 13 AM" src="https://github.com/user-attachments/assets/aae581c0-4c49-401b-8eb6-022d252a2998">

## 질문 혹은 공유 사항 (Optional)

2024-10-12 23:45 UTC, Mingyum-Kim requested changes
Resolver, Registry 구조가 잘 이해가 안되는데 .. 급한 PR이 아니라면 내일 설명해주세요 😉
수고했습니다 !

2024-10-12 23:45 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/domain/Loser.java
Participant를 재활용하지 않고 Loser를 만든 이유가 있나요?

2024-10-12 23:45 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/implement/BetParticipantResolver.java
> +	@Transactional
Implement 레이어에 트랜잭션을 건 이유가 있나요? 
조회만 하고 있는 것 같은데 read only = true설정도 필요할 것 같습니다!

2024-10-12 23:45 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/implement/ChatRoomDetailsFinder.java
> +	@Transactional(readOnly = true)
여기도 마찬가지입니다 !!

2024-10-13 08:36 UTC, ay-eonii approved these changes
예외처리도 해주시면 좋을 것 같아용 ㅎㅎ

2024-10-13 08:36 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/chat/domain/BetAttributes.java
> +	private final Long betId;
nullable 한가요?

2024-10-13 08:36 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/chat/implement/BetAttributeManager.java
> +		boolean isLoser = bet.isLoser(darakbangMember.getId());
내가 당첨자인지는 추가 기획을 고려하고 넣은신 건가여 ??

2024-10-14 04:45 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/domain/Loser.java
Loser 에 대한 요구사항이 변경될 수 있다고 생각했는데 지금은 불필요한 것 같네요. Participant로 교체했습니다.

2024-10-14 04:53 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/implement/BetParticipantResolver.java
> +	@Transactional
테스트의 lazyinitializationexception 문제 때문인데요. 서비스 코드에서 이미 트랜잭션을 열어준 상태라 좋지는 않아보입니다. 이것도 이슈로 달아두고 같이 고민해보시죠.

2024-10-14 04:53 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/implement/ChatRoomDetailsFinder.java
> +	@Transactional(readOnly = true)
이하동문~

2024-10-14 04:53 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/domain/BetAttributes.java
> +	private final Long betId;
아닙니다. 수정했어요~

2024-10-14 04:53 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/implement/BetAttributeManager.java
> +		boolean isLoser = bet.isLoser(darakbangMember.getId());
네 맞습니다. 프론트 로직상 필요한 경우가 있을 수 있어서 추가했습니다.

2024-10-14 05:19 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/chat/domain/Loser.java
반영 감사합니다 ~

2024-10-14 05:20 UTC, Mingyum-Kim approved these changes
수고하셨습니다 👍

2024-10-14 05:24 UTC, merged