채팅 알림 버그픽스
woowacourse-teams/2024-mouda pull request #687
Opened 2024-10-18 09:17 UTC by pricelees

## PR의 목적이 무엇인가요?

QA 과정에서 발생한 채팅 알림 관련 문제를 해결했습니다.

## 이슈 ID는 무엇인가요?

- #684 

## 설명

1. 모임 정보를 수정 시 알림 문제 
모임 정보 수정 시, 이름을 변경한 경우 변경된 이름으로 알림을 보내서 사용자에게 혼동을 줄 여지가 있다고 판단했습니다.
(예시) 원래 모임 이름이 "모임" 이고 변경된 모임 이름이 "모임12" 라면, 사용자에겐 "모임12" 정보가 바뀜 ~ 으로 알림이 나갔는데, 사용자 입장에서는 "모임12" 라는 모임에 들어간 적은 없으니 헷갈릴 수 있음..

따라서 이 경우 기존 모임 이름을 받아 기존 모임의 이름을 넣도록 수정했습니다.

2. 채팅 알림 메시지 형식 수정
이전 수정에서, 채팅 알림의 경우 아래와 같은 형식으로 알림이 전송됐었습니다.

**기존**
- 일반 채팅 전송시

[모임 / 베팅 이름]
모우다에서 보냄
[보낸사람]: [내용]

- 장소 / 시간 확정시

[모임 / 베팅 이름]
모우다에서 보냄
장소가 [장소]로 확정되었어요!

푸시 알림만 보면 어떤 모임에서 누가 메시지를 보냈는지 확실하게 나타나긴 하지만, 알림 센터에서 조회 시 "장소가 [장소]로 확정되었어요!" 인 메시지만 나타나 사용자가 어떤 모임인지 식별하기 힘들겠다는 생각으로 아래와 같이 조금 더 세분화하는 방식으로 수정했습니다.

**수정**
- 일반 채팅 전송시

[모임 / 베팅 이름]
모우다에서 보냄
[보낸사람]: [내용]

- 장소 / 시간 확정시

[다락방 이름]
모우다에서 보냄
'[모임이름]' 시간이 '[시간]'으로 확정되었어요!

3. 채팅 알림 구현 방법 수정
- 새로 추가된 Author와 ChatType을 활용하는 방식으로 수정했습니다. 처음에 ChatType을 사용할 땐 NotificationType을 더 이상 사용하지 않을 것으로 기대했으나, 알림 쪽 처리에서의 문제로 완전히 격리시킬 수는 없었습니다.

4. 베팅에서의 채팅은 알림이 안오는 문제 해결
- 일반 채팅방에서의 알림은 잘 오는데, 베팅에서는 알림이 오지 않고 에러도 발생하지 않아 디버깅할 수도 없었는데요, 어찌저찌하여 일부 코드를 수정했고 이제 정상 작동이 될 것 같습니다 ~

## 질문 혹은 공유 사항 (Optional)

2024-10-18 11:59 UTC, ay-eonii requested changes
고생하셨습니다 빠른 작업👍

코멘트 확인해주세용~~~

2024-10-18 11:59 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/moim/implement/sender/MoimNotificationSender.java
> +			.orElseThrow(() -> new DarakbangException(HttpStatus.NOT_FOUND, DarakbangErrorMessage.DARAKBANG_NOT_FOUND));
package에 해당하는 예외를 던져주기로 했던 것 같아요

2024-10-18 11:59 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/moim/implement/sender/MoimNotificationSender.java
> +			getMoimUrl(darakbang.getId(), darakbang.getId()),
두개 다 다락방 아이디 맞나여??

2024-10-20 05:42 UTC, pricelees reviewed
👍

2024-10-20 05:42 UTC, pricelees commented on backend/src/main/java/mouda/backend/moim/implement/sender/MoimNotificationSender.java
> +			.orElseThrow(() -> new DarakbangException(HttpStatus.NOT_FOUND, DarakbangErrorMessage.DARAKBANG_NOT_FOUND));
> package에 해당하는 예외를 던져주기로 했던 것 같아요

해당 이유로 알림 타입에 대한 예외는 모임 에러를 사용했는데, 여기서는 좀 애매한 감이 있어서 다락방 예외를 사용했어요 ㅋㅋ 말씀주신대로 모임예외로 수정하고, 예외 메시지를 "모임에 해당되는 다락방을 찾을 수 없음" 으로 수정할게요 ~

2024-10-20 05:42 UTC, pricelees commented on backend/src/main/java/mouda/backend/moim/implement/sender/MoimNotificationSender.java
> +			getMoimUrl(darakbang.getId(), darakbang.getId()),
> 두개 다 다락방 아이디 맞나여??

아뇨 ㅋㅋ 감사용 ㅋㅋ

2024-10-20 06:02 UTC, ay-eonii approved these changes
굿굿~👍

2024-10-20 07:29 UTC, ksk0605 requested changes
고생했어요 상돌!
간단한 변경사항만 수정 부탁드려요 😀

2024-10-20 07:29 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/domain/Author.java
> +		this.memberId = memberId;
다락방멤버 id 인지 그냥 memberid인지 구분할 수 있으면 좋겠네요!

2024-10-20 07:29 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/chat/util/ChatDateTimeFormatter.java
> +}
생성할 필요가 없는 클래스의 생성자는 private으로 닫아주세요!

2024-10-20 07:29 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/moim/implement/finder/ChatRecipientFinder.java
> +	// todo: 구버전 채팅 기능 삭제시 같이 지워주세요.
다음 버전에서 지우도록하죠!

2024-10-20 09:15 UTC, pricelees reviewed
하는김에 조금씩 더 다듬었어요 ~ㅎㅎ 확인 부탁요!

2024-10-20 09:15 UTC, pricelees commented on backend/src/main/java/mouda/backend/chat/util/ChatDateTimeFormatter.java
> +}
> 생성할 필요가 없는 클래스의 생성자는 private으로 닫아주세요!

넵 ~ 이왕 하는김에 조금 더 꼼꼼하게 처리해놨습니다 !

2024-10-20 09:15 UTC, pricelees commented on backend/src/main/java/mouda/backend/chat/domain/Author.java
> +		this.memberId = memberId;
> 다락방멤버 id 인지 그냥 memberid인지 구분할 수 있으면 좋겠네요!

수정했어요 ~

2024-10-20 13:37 UTC, ksk0605 approved these changes
수정 사항 확인했습니다! 고생했어요~

2024-10-21 04:59 UTC, merged