커스텀 예외 처리
woowacourse-teams/2024-mouda pull request #76
Opened 2024-07-18 08:26 UTC by ay-eonii

## PR의 목적이 무엇인가요?

- 커스텀 예외 핸들러를 추가했습니다.
- 모임 커스텀 예외를 추가했습니다.

## 이슈 ID는 무엇인가요?

- closed #71 

## 설명

예외 응답의 경우 아래와 같은 JSON 형태를 반환합니다.
```json
{
  "message": "모임이 존재하지 않습니다."
}
```

## 질문 혹은 공유 사항 (Optional)

2024-07-18 13:41 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/moim/service/MoimService.java
> +			.orElseThrow(() -> new MoimException(NOT_FOUND, MOIM_NOT_FOUND));
Moim 객체에서는 static import가 안되어 있지만 서비스에서는 되어있네요!

이 컨벤션에 대해 이야기 해보는 것도 좋을 것 같습니당

2024-07-18 13:44 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/exception/ServiceException.java
> +public class ServiceException extends RuntimeException {
현재 RuntimeException -> ServiceException -> MoimException 3개의 뎁스를 타고 있는 것 같아요.

혹시 ServiceException은 어떤 역할인가요..?!

2024-07-18 13:46 UTC, hoyeonyy requested changes
몇 가지 부분에 대해 내일 얘기해보면 좋을 것 같아요!

고생하셨습니다~!

2024-07-19 01:37 UTC, Mingyum-Kim reviewed
빠른 작업 좋아요! 👍
컨벤션에 대해서 같이 더 얘기해봅시다 ~

2024-07-19 01:37 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
> +}
MoimErrorMessage라고 자원이 명시된 경우라면 상수 이름의 Prefix에 Moim을 명시하지 않아도 될 것 같아요 !😄 
Moim이라는 도메인명이 바뀌게되면 같이 바뀌는 부분이 많아질까 하는 생각입니다.

+ static import를 사용한다면 더더욱 ..

2024-07-19 01:37 UTC, Mingyum-Kim commented on backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
> +		return ResponseEntity.status(e.getHttpStatus()).body(new ErrorResponse(e.getMessage()));
줄임말 e 대신에 exception으로 통일하는 게 좋을까요? 
이것도 컨벤션으로 정해봅시다!

2024-07-19 10:50 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/moim/service/MoimService.java
> +			.orElseThrow(() -> new MoimException(NOT_FOUND, MOIM_NOT_FOUND));
회의 내용 반영하여 static import 하지 않고, 필드에서 도메인 prefix는 제거했습니다~!

2024-07-19 10:50 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/moim/service/MoimService.java
> +			.orElseThrow(() -> new MoimException(NOT_FOUND, MOIM_NOT_FOUND));
회의 내용 반영하여 static import 하지 않고, 필드에서 도메인 prefix는 제거했습니다~!

2024-07-19 10:54 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
> +}
회의 내용 반영하여 static import 하지 않고, 필드에서 도메인 prefix는 제거했습니다~!

2024-07-19 10:56 UTC, ay-eonii commented on backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
> +		return ResponseEntity.status(e.getHttpStatus()).body(new ErrorResponse(e.getMessage()));
회의 시간에 다루지 못한 내용이지만 축약을 지양하고자 `exception`으로 변경 후 다시 리뷰 요청 드러요~

2024-07-19 11:01 UTC, ay-eonii commented
현재 `ServiceException` 클래스명을 `MoudaException`으로 변경했습니다! 

기존에 어떤 예외인지 인지하기 어렵다는 문제를 해결하고자 저희 서비스에서 규정하는 예외라는 의미를 담았습니다. 이견있으시다면 코멘트 부탁드려용 !~

2024-07-19 11:03 UTC, pricelees approved these changes
굿👍 빨리 퇴근하세욧!

2024-07-20 04:09 UTC, Mingyum-Kim approved these changes
고생했어요 테니 😄
이만 머지하겠습니다

2024-07-20 12:57 UTC, hoyeonyy approved these changes
굳굳 고생했어요 테니~~~👍

2024-07-20 14:31 UTC, merged