CORS 설정 수정
woowacourse-teams/2024-mouda pull request #88
Opened 2024-07-22 04:30 UTC by ksk0605

## PR의 목적이 무엇인가요?

## 이슈 ID는 무엇인가요?

- closed #87

## 설명

- [x] url 패턴 전체허용
- [x] 메소드 GET, POST, DELETE 허용
- [x] Authorization, Content-Type 헤더 허용
- [x] credential 적용

## 질문 혹은 공유 사항 (Optional)

2024-07-22 05:25 UTC, ay-eonii approved these changes
좋아요 테바 👍
블로그 글도 감사합닌다 ~

2024-07-22 13:17 UTC, hoyeonyy requested changes
테바 글도 쓰고 코드도 고치느랴 수고 많았습니다,,

method에 관한게 궁금해서 코멘트 하나 남겼습니다!

2024-07-22 13:17 UTC, hoyeonyy commented on backend/src/main/java/mouda/backend/config/CorsConfig.java
> +			.allowedMethods("GET", "POST", "DELETE")
OPTION 을 넣지 않아도 괜찮나요?!

2024-07-23 07:47 UTC, Mingyum-Kim approved these changes

2024-07-23 08:03 UTC, ksk0605 commented on backend/src/main/java/mouda/backend/config/CorsConfig.java
> +			.allowedMethods("GET", "POST", "DELETE")
실제 작동 테스트를 해보니 작동이 잘 되더라구요..? 
그래도 명시적으로 작성해놓는게 좋으니 수정하겠습니다!

2024-07-24 01:29 UTC, hoyeonyy approved these changes

2024-07-25 01:45 UTC, merged